Removing server from OMEVV Management
dell/omivv pull request #29
Opened 2022-11-21 12:50 UTC by Abhishek14-Dell

2022-12-20 06:01 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/omevvServerUnmanage.py
> +              return "Manage job is created successfully with id "+ str(data)
change the print statement- Unmanage

2022-12-20 06:02 UTC, pavithra-mahadev requested changes
Rebase and update for minor comment

2023-01-16 11:43 UTC, pavithra-mahadev approved these changes

2023-01-17 05:44 UTC, prasadrao-dell approved these changes

2023-01-17 05:44 UTC, merged