vCenter(s) unregistration
dell/omivv pull request #30
Opened 2022-11-21 18:18 UTC by Abhishek14-Dell

2022-12-21 09:47 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/unregisterVcenters.py
> +                unregistervcentershelper = UnregisterVcenters(base_url=base_url, omeIp=ARGS.ip, omeUsercredential=credential, vCenterUUID=ARGS.vcUUID[i], payload=payload, extensions=ARGS.extensions)
Can we have these parameters as part of create payload instead of constructor?

2022-12-21 09:48 UTC, pavithra-mahadev requested changes
try to rebase your branch

2023-01-16 12:10 UTC, pavithra-mahadev approved these changes

2023-01-17 05:44 UTC, prasadrao-dell approved these changes

2023-01-17 05:45 UTC, merged