Patch 1
dell/omivv pull request #42
Opened 2023-01-19 10:36 UTC by shuvaday

Updated with review comments.

2023-01-20 09:54 UTC, pavithra-mahadev requested changes

2023-01-20 09:54 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +from omevv.v1.omevv_apis_client.models import Credential, ShareCredential
Why do we need ShareCredential?

2023-01-20 09:54 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +        print('credential missing for sharedpath for CISF protocol')
typo - CIFS

2023-01-20 09:54 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +        print('Please pass valid sharedpath location for the provided protocl type')
typo - protocol

2023-01-20 09:54 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +    parser.add_argument('-protocol', help='protocol type', choices=['CIFS', 'NFS', 'HTTP', 'HTTPS', 'UNAVAILABLE'],
can we give UNAVAILABLE?

2023-01-20 09:57 UTC, shuvaday commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +from omevv.v1.omevv_apis_client.models import Credential, ShareCredential
for share path credentials for CIFS

2023-01-20 09:57 UTC, shuvaday commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +    parser.add_argument('-protocol', help='protocol type', choices=['CIFS', 'NFS', 'HTTP', 'HTTPS', 'UNAVAILABLE'],
dnt understand

2023-01-20 09:59 UTC, shuvaday commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +        print('credential missing for sharedpath for CISF protocol')
done

2023-01-20 09:59 UTC, shuvaday commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +        print('Please pass valid sharedpath location for the provided protocl type')
done

2023-01-20 11:30 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +        self.headers['x_omivv-api-vcenter-identifier'] = uuid
use constants

2023-01-20 11:32 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/CreateRepoProfile.py
> +from omevv.v1.omevv_apis_client.models import ErrorObject,protocol_type,profile_type,share_credential
remove one share_credential

2023-01-20 13:57 UTC, pavithra-mahadev approved these changes

2023-01-24 09:39 UTC, pavithra-mahadev approved these changes

2023-01-24 09:55 UTC, Abhishek14-Dell approved these changes

2023-01-31 10:08 UTC, prasadrao-dell approved these changes

2023-01-31 10:10 UTC, pavithra-mahadev approved these changes

2023-01-31 10:11 UTC, merged