Migration from OMIVV to OMEVV
dell/omivv pull request #54
Opened 2023-02-14 20:40 UTC by Abhishek14-Dell

2023-02-15 12:35 UTC, pavithra-mahadev requested changes

2023-02-15 12:35 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/omivvMigration.py
> +    unregister_val = input("Confirm unregister vCenter (Y/N): ")
from OMIVV

2023-02-15 12:35 UTC, pavithra-mahadev commented on Python/omevv/v1/scripts/omivvMigration.py
> +    discover_server = input("Discover Server Device (Y/N): ")
Are the servers discovered in OME?

2023-03-15 06:39 UTC, pavithra-mahadev approved these changes

2023-03-15 08:25 UTC, prasadrao-dell approved these changes

2023-03-15 12:53 UTC, merged